<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE stylesheet>
<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform">
<!-- This file generated by generate_MARC21Languages.pl -->
 <xsl:template name="languageCodeText">
 <xsl:param name="code"/>
 <xsl:choose>
 <xsl:when test="$code='abk'"><xsl:text>الأبخازية</xsl:text></xsl:when>
 <xsl:when test="$code='ace'"><xsl:text>الصينية</xsl:text></xsl:when>
 <xsl:when test="$code='ach'"><xsl:text>الأتشولية</xsl:text></xsl:when>
 <xsl:when test="$code='ada'"><xsl:text>الدانغمية</xsl:text></xsl:when>
 <xsl:when test="$code='ady'"><xsl:text>الأديغية</xsl:text></xsl:when>
 <xsl:when test="$code='aar'"><xsl:text>العفارية</xsl:text></xsl:when>
 <xsl:when test="$code='afh'"><xsl:text>الأفريلي (لغة اصطناعية)</xsl:text></xsl:when>
 <xsl:when test="$code='afr'"><xsl:text>الأفريكانية</xsl:text></xsl:when>
 <xsl:when test="$code='afa'"><xsl:text>أفروآسيوية (أخرى)</xsl:text></xsl:when>
 <xsl:when test="$code='ain'"><xsl:text>الآينوية</xsl:text></xsl:when>
 <xsl:when test="$code='aka'"><xsl:text>الأكانية</xsl:text></xsl:when>
 <xsl:when test="$code='akk'"><xsl:text>الأكادية</xsl:text></xsl:when>
 <xsl:when test="$code='alb'"><xsl:text>الألبانية</xsl:text></xsl:when>
 <xsl:when test="$code='ale'"><xsl:text>الأليوتية</xsl:text></xsl:when>
 <xsl:when test="$code='alg'"><xsl:text>الألغونكوية (أخرى)</xsl:text></xsl:when>
 <xsl:when test="$code='alt'"><xsl:text>الألطائية</xsl:text></xsl:when>
 <xsl:when test="$code='tut'"><xsl:text>الألطائية (أخرى)</xsl:text></xsl:when>
 <xsl:when test="$code='amh'"><xsl:text>الأمهرية</xsl:text></xsl:when>
 <xsl:when test="$code='anp'"><xsl:text>الأنجيكية</xsl:text></xsl:when>
 <xsl:when test="$code='apa'"><xsl:text>اللغات الأباتشية</xsl:text></xsl:when>
 <xsl:when test="$code='ara'"><xsl:text>عربي</xsl:text></xsl:when>
 <xsl:when test="$code='arg'"><xsl:text>الأراغونية</xsl:text></xsl:when>
 <xsl:when test="$code='arc'"><xsl:text>الآرامية</xsl:text></xsl:when>
 <xsl:when test="$code='arp'"><xsl:text>الأراباهو</xsl:text></xsl:when>
 <xsl:when test="$code='arw'"><xsl:text>الأراواكية</xsl:text></xsl:when>
 <xsl:when test="$code='arm'"><xsl:text>الأرمينية</xsl:text></xsl:when>
 <xsl:when test="$code='rup'"><xsl:text>الأرومونية</xsl:text></xsl:when>
 <xsl:when test="$code='art'"><xsl:text>اصطناعية (أخرى)</xsl:text></xsl:when>
 <xsl:when test="$code='asm'"><xsl:text>الأسامية</xsl:text></xsl:when>
 <xsl:when test="$code='ath'"><xsl:text>الأثابسكانية (أخرى)</xsl:text></xsl:when>
 <xsl:when test="$code='aus'"><xsl:text>اللغات الأسترالية</xsl:text></xsl:when>
 <xsl:when test="$code='map'"><xsl:text>الأسترونيزية (أخرى)</xsl:text></xsl:when>
 <xsl:when test="$code='ava'"><xsl:text>الأوارية</xsl:text></xsl:when>
 <xsl:when test="$code='ave'"><xsl:text>الأفستية</xsl:text></xsl:when>
 <xsl:when test="$code='awa'"><xsl:text>الأوادية</xsl:text></xsl:when>
 <xsl:when test="$code='aym'"><xsl:text>الأيمرية</xsl:text></xsl:when>
 <xsl:when test="$code='aze'"><xsl:text>الأذريبيجانية</xsl:text></xsl:when>
 <xsl:when test="$code='ast'"><xsl:text>بابل</xsl:text></xsl:when>
 <xsl:when test="$code='ban'"><xsl:text>البالينية</xsl:text></xsl:when>
 <xsl:when test="$code='bat'"><xsl:text>البلطيقية (أخرى)</xsl:text></xsl:when>
 <xsl:when test="$code='bal'"><xsl:text>البلوشية</xsl:text></xsl:when>
 <xsl:when test="$code='bam'"><xsl:text>البمبارا</xsl:text></xsl:when>
 <xsl:when test="$code='bai'"><xsl:text>اللغات الباميليكية</xsl:text></xsl:when>
 <xsl:when test="$code='bad'"><xsl:text>لغات البندا</xsl:text></xsl:when>
 <xsl:when test="$code='bnt'"><xsl:text>البانتو (أخرى)</xsl:text></xsl:when>
 <xsl:when test="$code='bas'"><xsl:text>الباسا</xsl:text></xsl:when>
 <xsl:when test="$code='bak'"><xsl:text>الباشكيرية</xsl:text></xsl:when>
 <xsl:when test="$code='baq'"><xsl:text>الباسكية</xsl:text></xsl:when>
 <xsl:when test="$code='btk'"><xsl:text>الباتاك</xsl:text></xsl:when>
 <xsl:when test="$code='bej'"><xsl:text>البيجا</xsl:text></xsl:when>
 <xsl:when test="$code='bel'"><xsl:text>البيلاروسية</xsl:text></xsl:when>
 <xsl:when test="$code='bem'"><xsl:text>البيمبا</xsl:text></xsl:when>
 <xsl:when test="$code='ben'"><xsl:text>البنغالية</xsl:text></xsl:when>
 <xsl:when test="$code='ber'"><xsl:text>البربرية (أخرى)</xsl:text></xsl:when>
 <xsl:when test="$code='bho'"><xsl:text>البهوجبرية</xsl:text></xsl:when>
 <xsl:when test="$code='bih'"><xsl:text>البهارية (أخرى)</xsl:text></xsl:when>
 <xsl:when test="$code='bik'"><xsl:text>البيكولية</xsl:text></xsl:when>
 <xsl:when test="$code='byn'"><xsl:text>البلينية</xsl:text></xsl:when>
 <xsl:when test="$code='bis'"><xsl:text>البسلاما</xsl:text></xsl:when>
 <xsl:when test="$code='zbl'"><xsl:text>Blissymbolics</xsl:text></xsl:when>
 <xsl:when test="$code='bos'"><xsl:text>البوسنية</xsl:text></xsl:when>
 <xsl:when test="$code='bra'"><xsl:text>البرجية</xsl:text></xsl:when>
 <xsl:when test="$code='bre'"><xsl:text>البريتانية</xsl:text></xsl:when>
 <xsl:when test="$code='bug'"><xsl:text>البوقسية</xsl:text></xsl:when>
 <xsl:when test="$code='bul'"><xsl:text>البلغارية</xsl:text></xsl:when>
 <xsl:when test="$code='bua'"><xsl:text>البوريات</xsl:text></xsl:when>
 <xsl:when test="$code='bur'"><xsl:text>البورمية</xsl:text></xsl:when>
 <xsl:when test="$code='cad'"><xsl:text>الكادو</xsl:text></xsl:when>
 <xsl:when test="$code='car'"><xsl:text>الكاريبية</xsl:text></xsl:when>
 <xsl:when test="$code='cat'"><xsl:text>الكاتالونية</xsl:text></xsl:when>
 <xsl:when test="$code='cau'"><xsl:text>القوقازية (أخرى)</xsl:text></xsl:when>
 <xsl:when test="$code='ceb'"><xsl:text>السيبوانية</xsl:text></xsl:when>
 <xsl:when test="$code='cel'"><xsl:text>السلتية (أخرى)</xsl:text></xsl:when>
 <xsl:when test="$code='cai'"><xsl:text>الهندية الأمريكية الوسطى (أخرى)</xsl:text></xsl:when>
 <xsl:when test="$code='chg'"><xsl:text>الجغتائية</xsl:text></xsl:when>
 <xsl:when test="$code='cmc'"><xsl:text>اللغات التشاميكية</xsl:text></xsl:when>
 <xsl:when test="$code='cha'"><xsl:text>التشاموروية</xsl:text></xsl:when>
 <xsl:when test="$code='che'"><xsl:text>الشيشانية</xsl:text></xsl:when>
 <xsl:when test="$code='chr'"><xsl:text>الشيروكى</xsl:text></xsl:when>
 <xsl:when test="$code='chy'"><xsl:text>الشايان</xsl:text></xsl:when>
 <xsl:when test="$code='chb'"><xsl:text>التشيبشا</xsl:text></xsl:when>
 <xsl:when test="$code='chi'"><xsl:text>الصينية</xsl:text></xsl:when>
 <xsl:when test="$code='chn'"><xsl:text>الشينوك جارجون</xsl:text></xsl:when>
 <xsl:when test="$code='chp'"><xsl:text>الشيباوايان</xsl:text></xsl:when>
 <xsl:when test="$code='cho'"><xsl:text>الشوكتو</xsl:text></xsl:when>
 <xsl:when test="$code='chu'"><xsl:text>السلافية الكنسية</xsl:text></xsl:when>
 <xsl:when test="$code='chk'"><xsl:text>التشكيزية</xsl:text></xsl:when>
 <xsl:when test="$code='chv'"><xsl:text>التشوفاشية</xsl:text></xsl:when>
 <xsl:when test="$code='cop'"><xsl:text>القبطية</xsl:text></xsl:when>
 <xsl:when test="$code='cor'"><xsl:text>الكورنية</xsl:text></xsl:when>
 <xsl:when test="$code='cos'"><xsl:text>الكورسية</xsl:text></xsl:when>
 <xsl:when test="$code='cre'"><xsl:text>الكيرية</xsl:text></xsl:when>
 <xsl:when test="$code='mus'"><xsl:text>الكريك</xsl:text></xsl:when>
 <xsl:when test="$code='crp'"><xsl:text>الكريولىة واللغات المبسطة الأخرى للتفاهم بين الشعوب (أخرى)</xsl:text></xsl:when>
 <xsl:when test="$code='cpe'"><xsl:text>الكريولية واللغات المبسطة الأخرى للتفاهم بين الشعوب على أساس الإنجليزية (أخرى)</xsl:text></xsl:when>
 <xsl:when test="$code='cpf'"><xsl:text>الكريولية واللغات المبسطة الأخرى للتفاهم بين الشعوب على أساس الفرنسية (أخرى)</xsl:text></xsl:when>
 <xsl:when test="$code='cpp'"><xsl:text>الكريولية واللغات المبسطة الأخرى للتفاهم بين الشعوب على أساس البرتغالية (أخرى)</xsl:text></xsl:when>
 <xsl:when test="$code='crh'"><xsl:text>التتارية القرمية</xsl:text></xsl:when>
 <xsl:when test="$code='hrv'"><xsl:text>الكرواتية</xsl:text></xsl:when>
 <xsl:when test="$code='cus'"><xsl:text>الكشيتيك (أخرى)</xsl:text></xsl:when>
 <xsl:when test="$code='cze'"><xsl:text>التشيكية</xsl:text></xsl:when>
 <xsl:when test="$code='dak'"><xsl:text>الداكوتا</xsl:text></xsl:when>
 <xsl:when test="$code='dan'"><xsl:text>الدانماركية</xsl:text></xsl:when>
 <xsl:when test="$code='dar'"><xsl:text>الدارجوا</xsl:text></xsl:when>
 <xsl:when test="$code='day'"><xsl:text>الدياك</xsl:text></xsl:when>
 <xsl:when test="$code='del'"><xsl:text>ديلاوير</xsl:text></xsl:when>
 <xsl:when test="$code='din'"><xsl:text>الدنكا</xsl:text></xsl:when>
 <xsl:when test="$code='div'"><xsl:text>المالديفية</xsl:text></xsl:when>
 <xsl:when test="$code='doi'"><xsl:text>الدورجية</xsl:text></xsl:when>
 <xsl:when test="$code='dgr'"><xsl:text>الدورجية</xsl:text></xsl:when>
 <xsl:when test="$code='dra'"><xsl:text>الدرفيدية (أخرى)</xsl:text></xsl:when>
 <xsl:when test="$code='dua'"><xsl:text>الدوالا</xsl:text></xsl:when>
 <xsl:when test="$code='dut'"><xsl:text>الهولندية</xsl:text></xsl:when>
 <xsl:when test="$code='dum'"><xsl:text>الهولندية الوسطى (1050-1350)</xsl:text></xsl:when>
 <xsl:when test="$code='dyu'"><xsl:text>الديولا</xsl:text></xsl:when>
 <xsl:when test="$code='dzo'"><xsl:text>الدزونخية</xsl:text></xsl:when>
 <xsl:when test="$code='frs'"><xsl:text>الفريزية الشرقية</xsl:text></xsl:when>
 <xsl:when test="$code='bin'"><xsl:text>إيدو</xsl:text></xsl:when>
 <xsl:when test="$code='efi'"><xsl:text>إفيك</xsl:text></xsl:when>
 <xsl:when test="$code='egy'"><xsl:text>المصرية</xsl:text></xsl:when>
 <xsl:when test="$code='eka'"><xsl:text>إكاجوك</xsl:text></xsl:when>
 <xsl:when test="$code='elx'"><xsl:text>العيلامية</xsl:text></xsl:when>
 <xsl:when test="$code='eng'"><xsl:text>الإنجليزية</xsl:text></xsl:when>
 <xsl:when test="$code='enm'"><xsl:text>الإنجليزية الوسطى (1100-1500)</xsl:text></xsl:when>
 <xsl:when test="$code='ang'"><xsl:text>الإنجليزية القديمة (450-1100)</xsl:text></xsl:when>
 <xsl:when test="$code='myv'"><xsl:text>الأرزية</xsl:text></xsl:when>
 <xsl:when test="$code='epo'"><xsl:text>الإسبرانتو</xsl:text></xsl:when>
 <xsl:when test="$code='est'"><xsl:text>الإستونية</xsl:text></xsl:when>
 <xsl:when test="$code='gez'"><xsl:text>الإثيوبية</xsl:text></xsl:when>
 <xsl:when test="$code='ewe'"><xsl:text>إيوي</xsl:text></xsl:when>
 <xsl:when test="$code='ewo'"><xsl:text>الإوندو</xsl:text></xsl:when>
 <xsl:when test="$code='fan'"><xsl:text>الفانج</xsl:text></xsl:when>
 <xsl:when test="$code='fat'"><xsl:text>الفانتي</xsl:text></xsl:when>
 <xsl:when test="$code='fao'"><xsl:text>الفاروسية</xsl:text></xsl:when>
 <xsl:when test="$code='fij'"><xsl:text>الفيجية</xsl:text></xsl:when>
 <xsl:when test="$code='fil'"><xsl:text>الفلبينية</xsl:text></xsl:when>
 <xsl:when test="$code='fin'"><xsl:text>الفنلندية</xsl:text></xsl:when>
 <xsl:when test="$code='fiu'"><xsl:text> الفنلندية-الأوغرية (أخرى)</xsl:text></xsl:when>
 <xsl:when test="$code='fon'"><xsl:text>الفون</xsl:text></xsl:when>
 <xsl:when test="$code='fre'"><xsl:text>الفرنسية</xsl:text></xsl:when>
 <xsl:when test="$code='frm'"><xsl:text>الفرنسية الوسطى (1400-1600)</xsl:text></xsl:when>
 <xsl:when test="$code='fro'"><xsl:text>الفرنسية القديمة (842-1300)</xsl:text></xsl:when>
 <xsl:when test="$code='fry'"><xsl:text>الفريزية</xsl:text></xsl:when>
 <xsl:when test="$code='fur'"><xsl:text>الفريولية</xsl:text></xsl:when>
 <xsl:when test="$code='ful'"><xsl:text>الفولا</xsl:text></xsl:when>
 <xsl:when test="$code='gaa'"><xsl:text>غا</xsl:text></xsl:when>
 <xsl:when test="$code='glg'"><xsl:text>الغاليكية</xsl:text></xsl:when>
 <xsl:when test="$code='lug'"><xsl:text>الغندية</xsl:text></xsl:when>
 <xsl:when test="$code='gay'"><xsl:text>الجايو</xsl:text></xsl:when>
 <xsl:when test="$code='gba'"><xsl:text>الجبايا</xsl:text></xsl:when>
 <xsl:when test="$code='geo'"><xsl:text>الجورجية</xsl:text></xsl:when>
 <xsl:when test="$code='ger'"><xsl:text>الألمانية</xsl:text></xsl:when>
 <xsl:when test="$code='gmh'"><xsl:text>الألمانية العليا الوسطى (1050-1500)</xsl:text></xsl:when>
 <xsl:when test="$code='goh'"><xsl:text>الألمانية العليا القديمة (750-1050)</xsl:text></xsl:when>
 <xsl:when test="$code='gem'"><xsl:text>الجرمانية (أخرى)</xsl:text></xsl:when>
 <xsl:when test="$code='gil'"><xsl:text>لغة جبل طارق</xsl:text></xsl:when>
 <xsl:when test="$code='gon'"><xsl:text>غوندي</xsl:text></xsl:when>
 <xsl:when test="$code='gor'"><xsl:text>جورونتالو</xsl:text></xsl:when>
 <xsl:when test="$code='got'"><xsl:text>القوطية</xsl:text></xsl:when>
 <xsl:when test="$code='grb'"><xsl:text>غريبو</xsl:text></xsl:when>
 <xsl:when test="$code='grc'"><xsl:text>اليونانية القديمة (حتى 1453)</xsl:text></xsl:when>
 <xsl:when test="$code='gre'"><xsl:text>اليونانية الحديثة (1453-)</xsl:text></xsl:when>
 <xsl:when test="$code='grn'"><xsl:text>الغوارانية</xsl:text></xsl:when>
 <xsl:when test="$code='guj'"><xsl:text>الكجراتية</xsl:text></xsl:when>
 <xsl:when test="$code='gwi'"><xsl:text>جوتشين</xsl:text></xsl:when>
 <xsl:when test="$code='hai'"><xsl:text>هيدا</xsl:text></xsl:when>
 <xsl:when test="$code='hat'"><xsl:text>الكريولية الفرنسية الهايتية</xsl:text></xsl:when>
 <xsl:when test="$code='hau'"><xsl:text>الهوسا</xsl:text></xsl:when>
 <xsl:when test="$code='haw'"><xsl:text>الهاوايية</xsl:text></xsl:when>
 <xsl:when test="$code='heb'"><xsl:text>العبرية</xsl:text></xsl:when>
 <xsl:when test="$code='her'"><xsl:text>هيريرو</xsl:text></xsl:when>
 <xsl:when test="$code='hil'"><xsl:text>الهيليجينون</xsl:text></xsl:when>
 <xsl:when test="$code='hin'"><xsl:text>الهندية</xsl:text></xsl:when>
 <xsl:when test="$code='hmo'"><xsl:text>هيري موتو</xsl:text></xsl:when>
 <xsl:when test="$code='hit'"><xsl:text>الحيثية</xsl:text></xsl:when>
 <xsl:when test="$code='hmn'"><xsl:text>الهمونجية</xsl:text></xsl:when>
 <xsl:when test="$code='hun'"><xsl:text>المجرية</xsl:text></xsl:when>
 <xsl:when test="$code='hup'"><xsl:text>هوبا</xsl:text></xsl:when>
 <xsl:when test="$code='iba'"><xsl:text>إيبان</xsl:text></xsl:when>
 <xsl:when test="$code='ice'"><xsl:text>الأيسلندية</xsl:text></xsl:when>
 <xsl:when test="$code='ido'"><xsl:text>آيدو</xsl:text></xsl:when>
 <xsl:when test="$code='ibo'"><xsl:text>إيجبو</xsl:text></xsl:when>
 <xsl:when test="$code='ijo'"><xsl:text>الجوت</xsl:text></xsl:when>
 <xsl:when test="$code='ilo'"><xsl:text>إيلوكانو</xsl:text></xsl:when>
 <xsl:when test="$code='smn'"><xsl:text>إيناري سامي</xsl:text></xsl:when>
 <xsl:when test="$code='inc'"><xsl:text>الهندية (أخرى)</xsl:text></xsl:when>
 <xsl:when test="$code='ine'"><xsl:text>الهندية الأوروبية (أخرى)</xsl:text></xsl:when>
 <xsl:when test="$code='ind'"><xsl:text>الإندونيسية</xsl:text></xsl:when>
 <xsl:when test="$code='inh'"><xsl:text>الأنغوشي</xsl:text></xsl:when>
 <xsl:when test="$code='ina'"><xsl:text>إنترلنغوا (جمعية اللغة الدولية المساعدة)</xsl:text></xsl:when>
 <xsl:when test="$code='ile'"><xsl:text>إنترلنغوا</xsl:text></xsl:when>
 <xsl:when test="$code='iku'"><xsl:text>الإنكتيتوتية</xsl:text></xsl:when>
 <xsl:when test="$code='ipk'"><xsl:text>الإينبياك</xsl:text></xsl:when>
 <xsl:when test="$code='ira'"><xsl:text>الإيرانية (أخرى)</xsl:text></xsl:when>
 <xsl:when test="$code='gle'"><xsl:text>الأيرلندية</xsl:text></xsl:when>
 <xsl:when test="$code='mga'"><xsl:text>الأيرلندية الوسطى (1100-1550)</xsl:text></xsl:when>
 <xsl:when test="$code='sga'"><xsl:text>الأيرلندية القديمة (إلى 1100)</xsl:text></xsl:when>
 <xsl:when test="$code='iro'"><xsl:text>الإيروكيان (أخرى)</xsl:text></xsl:when>
 <xsl:when test="$code='ita'"><xsl:text>الإيطالية</xsl:text></xsl:when>
 <xsl:when test="$code='jpn'"><xsl:text>اليابانية</xsl:text></xsl:when>
 <xsl:when test="$code='jav'"><xsl:text>الجاوية</xsl:text></xsl:when>
 <xsl:when test="$code='jrb'"><xsl:text>اليهودية العربية</xsl:text></xsl:when>
 <xsl:when test="$code='jpr'"><xsl:text>اليهودية الفارسية</xsl:text></xsl:when>
 <xsl:when test="$code='kbd'"><xsl:text>القبردية</xsl:text></xsl:when>
 <xsl:when test="$code='kab'"><xsl:text>القبائل</xsl:text></xsl:when>
 <xsl:when test="$code='kac'"><xsl:text>الكاشينية</xsl:text></xsl:when>
 <xsl:when test="$code='kal'"><xsl:text>كالاديسوت</xsl:text></xsl:when>
 <xsl:when test="$code='kam'"><xsl:text>الكامبا</xsl:text></xsl:when>
 <xsl:when test="$code='kan'"><xsl:text>الكنادية</xsl:text></xsl:when>
 <xsl:when test="$code='kau'"><xsl:text>الكانوري</xsl:text></xsl:when>
 <xsl:when test="$code='krc'"><xsl:text>الكاراتشاي-بالكا</xsl:text></xsl:when>
 <xsl:when test="$code='kaa'"><xsl:text>كارا-كالباك</xsl:text></xsl:when>
 <xsl:when test="$code='krl'"><xsl:text>الكاريلية</xsl:text></xsl:when>
 <xsl:when test="$code='kar'"><xsl:text>اللغات الكارينية</xsl:text></xsl:when>
 <xsl:when test="$code='kas'"><xsl:text>الكشميرية</xsl:text></xsl:when>
 <xsl:when test="$code='csb'"><xsl:text>الكاشبايان</xsl:text></xsl:when>
 <xsl:when test="$code='kaw'"><xsl:text>الجاوية القديمة</xsl:text></xsl:when>
 <xsl:when test="$code='kaz'"><xsl:text>الكازاخية</xsl:text></xsl:when>
 <xsl:when test="$code='kha'"><xsl:text>الكازية</xsl:text></xsl:when>
 <xsl:when test="$code='khm'"><xsl:text>الخميرية</xsl:text></xsl:when>
 <xsl:when test="$code='khi'"><xsl:text>لغات خويسان (أخرى)</xsl:text></xsl:when>
 <xsl:when test="$code='kho'"><xsl:text>الختنية</xsl:text></xsl:when>
 <xsl:when test="$code='kik'"><xsl:text>الكيكويو</xsl:text></xsl:when>
 <xsl:when test="$code='kmb'"><xsl:text>كيمبوندو</xsl:text></xsl:when>
 <xsl:when test="$code='kin'"><xsl:text>الكينيارواندية</xsl:text></xsl:when>
 <xsl:when test="$code='tlh'"><xsl:text>كلينجون (لغة اصطناعية)</xsl:text></xsl:when>
 <xsl:when test="$code='kom'"><xsl:text>كومي</xsl:text></xsl:when>
 <xsl:when test="$code='kon'"><xsl:text>الكونغو</xsl:text></xsl:when>
 <xsl:when test="$code='kok'"><xsl:text>الكونكانية</xsl:text></xsl:when>
 <xsl:when test="$code='kut'"><xsl:text>كوتيناي</xsl:text></xsl:when>
 <xsl:when test="$code='kor'"><xsl:text>الكورية</xsl:text></xsl:when>
 <xsl:when test="$code='kos'"><xsl:text>الكورية</xsl:text></xsl:when>
 <xsl:when test="$code='kpe'"><xsl:text>الكبيلي</xsl:text></xsl:when>
 <xsl:when test="$code='kro'"><xsl:text>كرو (أخرى)</xsl:text></xsl:when>
 <xsl:when test="$code='kua'"><xsl:text>الكيونياما</xsl:text></xsl:when>
 <xsl:when test="$code='kum'"><xsl:text>القوموقية</xsl:text></xsl:when>
 <xsl:when test="$code='kur'"><xsl:text>الكردية</xsl:text></xsl:when>
 <xsl:when test="$code='kru'"><xsl:text>الكوروخ</xsl:text></xsl:when>
 <xsl:when test="$code='kir'"><xsl:text>القيرغيزية</xsl:text></xsl:when>
 <xsl:when test="$code='lad'"><xsl:text>الإسبانية اليهودية</xsl:text></xsl:when>
 <xsl:when test="$code='lah'"><xsl:text>لاهندا</xsl:text></xsl:when>
 <xsl:when test="$code='lam'"><xsl:text>لامبا (زامبيا والكونغو)</xsl:text></xsl:when>
 <xsl:when test="$code='lao'"><xsl:text>لاو</xsl:text></xsl:when>
 <xsl:when test="$code='lat'"><xsl:text>اللاتينية</xsl:text></xsl:when>
 <xsl:when test="$code='lav'"><xsl:text>اللاتفية</xsl:text></xsl:when>
 <xsl:when test="$code='lez'"><xsl:text>الليزغينية</xsl:text></xsl:when>
 <xsl:when test="$code='lim'"><xsl:text>الليمبرجيشية</xsl:text></xsl:when>
 <xsl:when test="$code='lin'"><xsl:text>اللينجالا</xsl:text></xsl:when>
 <xsl:when test="$code='lit'"><xsl:text>اللتوانية</xsl:text></xsl:when>
 <xsl:when test="$code='jbo'"><xsl:text>لجبان (لغة اصطناعية)</xsl:text></xsl:when>
 <xsl:when test="$code='nds'"><xsl:text>الألمانية السفلى</xsl:text></xsl:when>
 <xsl:when test="$code='dsb'"><xsl:text>الصربية السفلى</xsl:text></xsl:when>
 <xsl:when test="$code='loz'"><xsl:text>اللوزية</xsl:text></xsl:when>
 <xsl:when test="$code='lub'"><xsl:text>لوبا-كاتانغا</xsl:text></xsl:when>
 <xsl:when test="$code='lua'"><xsl:text>لوبا لولوا</xsl:text></xsl:when>
 <xsl:when test="$code='lui'"><xsl:text>لويسينيو</xsl:text></xsl:when>
 <xsl:when test="$code='smj'"><xsl:text>لوله سامي </xsl:text></xsl:when>
 <xsl:when test="$code='lun'"><xsl:text>لوندا</xsl:text></xsl:when>
 <xsl:when test="$code='luo'"><xsl:text>لوه (كينيا وتنزانيا)</xsl:text></xsl:when>
 <xsl:when test="$code='lus'"><xsl:text>لوشاي</xsl:text></xsl:when>
 <xsl:when test="$code='ltz'"><xsl:text>اللوكسمبرجية</xsl:text></xsl:when>
 <xsl:when test="$code='mac'"><xsl:text>المقدونية</xsl:text></xsl:when>
 <xsl:when test="$code='mad'"><xsl:text>المادريز</xsl:text></xsl:when>
 <xsl:when test="$code='mag'"><xsl:text>ماجاهي </xsl:text></xsl:when>
 <xsl:when test="$code='mai'"><xsl:text>المايثيلية</xsl:text></xsl:when>
 <xsl:when test="$code='mak'"><xsl:text>ماكسار</xsl:text></xsl:when>
 <xsl:when test="$code='mlg'"><xsl:text>المالاغاسية</xsl:text></xsl:when>
 <xsl:when test="$code='may'"><xsl:text>الماليزية</xsl:text></xsl:when>
 <xsl:when test="$code='mal'"><xsl:text>المالايالامية</xsl:text></xsl:when>
 <xsl:when test="$code='mlt'"><xsl:text>المالطية</xsl:text></xsl:when>
 <xsl:when test="$code='mnc'"><xsl:text>المانشو</xsl:text></xsl:when>
 <xsl:when test="$code='mdr'"><xsl:text>مندر</xsl:text></xsl:when>
 <xsl:when test="$code='man'"><xsl:text>مندينكا</xsl:text></xsl:when>
 <xsl:when test="$code='mni'"><xsl:text>مانيبوري</xsl:text></xsl:when>
 <xsl:when test="$code='mno'"><xsl:text>لغات مانوبو</xsl:text></xsl:when>
 <xsl:when test="$code='glv'"><xsl:text>المنكية</xsl:text></xsl:when>
 <xsl:when test="$code='mao'"><xsl:text>الماورية</xsl:text></xsl:when>
 <xsl:when test="$code='arn'"><xsl:text>المابوتشي</xsl:text></xsl:when>
 <xsl:when test="$code='mar'"><xsl:text>المهاراتية</xsl:text></xsl:when>
 <xsl:when test="$code='chm'"><xsl:text>الماري</xsl:text></xsl:when>
 <xsl:when test="$code='mah'"><xsl:text>المارشالية</xsl:text></xsl:when>
 <xsl:when test="$code='mwr'"><xsl:text>الماروارية</xsl:text></xsl:when>
 <xsl:when test="$code='mas'"><xsl:text>الماساي</xsl:text></xsl:when>
 <xsl:when test="$code='myn'"><xsl:text>لغات المايا</xsl:text></xsl:when>
 <xsl:when test="$code='men'"><xsl:text>المندي</xsl:text></xsl:when>
 <xsl:when test="$code='mic'"><xsl:text>الميكماكيونية</xsl:text></xsl:when>
 <xsl:when test="$code='min'"><xsl:text>مينانغكابو</xsl:text></xsl:when>
 <xsl:when test="$code='mwl'"><xsl:text>الميراندية</xsl:text></xsl:when>
 <xsl:when test="$code='mis'"><xsl:text>لغات متنوعة</xsl:text></xsl:when>
 <xsl:when test="$code='moh'"><xsl:text>موهوك</xsl:text></xsl:when>
 <xsl:when test="$code='mdf'"><xsl:text>الموكشا</xsl:text></xsl:when>
 <xsl:when test="$code='mkh'"><xsl:text> المونية الخميرية (أخرى)</xsl:text></xsl:when>
 <xsl:when test="$code='lol'"><xsl:text>مونجو-نكوندو</xsl:text></xsl:when>
 <xsl:when test="$code='mon'"><xsl:text>المنغولية</xsl:text></xsl:when>
 <xsl:when test="$code='cnr'"><xsl:text>المونتنغرية </xsl:text></xsl:when>
 <xsl:when test="$code='mos'"><xsl:text>موري</xsl:text></xsl:when>
 <xsl:when test="$code='mul'"><xsl:text>لغات متعددة</xsl:text></xsl:when>
 <xsl:when test="$code='mun'"><xsl:text>الموندا (أخرى)</xsl:text></xsl:when>
 <xsl:when test="$code='nah'"><xsl:text>الناهواتل</xsl:text></xsl:when>
 <xsl:when test="$code='nau'"><xsl:text>ناورو</xsl:text></xsl:when>
 <xsl:when test="$code='nav'"><xsl:text>النافاهو</xsl:text></xsl:when>
 <xsl:when test="$code='nbl'"><xsl:text>نديبيلي (جنوب إفريقيا)</xsl:text></xsl:when>
 <xsl:when test="$code='nde'"><xsl:text>نديبيلي (زيمبابوي)</xsl:text></xsl:when>
 <xsl:when test="$code='ndo'"><xsl:text>ندونغا</xsl:text></xsl:when>
 <xsl:when test="$code='nap'"><xsl:text>الإيطالية النابولية</xsl:text></xsl:when>
 <xsl:when test="$code='nep'"><xsl:text>النيبالية</xsl:text></xsl:when>
 <xsl:when test="$code='new'"><xsl:text>النيواري</xsl:text></xsl:when>
 <xsl:when test="$code='nwc'"><xsl:text>النيواري القديم</xsl:text></xsl:when>
 <xsl:when test="$code='nia'"><xsl:text>النياس</xsl:text></xsl:when>
 <xsl:when test="$code='nic'"><xsl:text>النيجر-كردفانيان (أخرى)</xsl:text></xsl:when>
 <xsl:when test="$code='ssa'"><xsl:text>الصحراوية النيلية (أخرى)</xsl:text></xsl:when>
 <xsl:when test="$code='niu'"><xsl:text>النيوي</xsl:text></xsl:when>
 <xsl:when test="$code='nqo'"><xsl:text>النكو</xsl:text></xsl:when>
 <xsl:when test="$code='nog'"><xsl:text>النوجاى</xsl:text></xsl:when>
 <xsl:when test="$code='zxx'"><xsl:text>لا يوجد محتوى لغوي</xsl:text></xsl:when>
 <xsl:when test="$code='nai'"><xsl:text>الهندية الأمريكية الشمالية (أخرى)</xsl:text></xsl:when>
 <xsl:when test="$code='frr'"><xsl:text>الفريزية الشمالية</xsl:text></xsl:when>
 <xsl:when test="$code='sme'"><xsl:text>السامي الشمالية</xsl:text></xsl:when>
 <xsl:when test="$code='nso'"><xsl:text>السوثو الشمالية</xsl:text></xsl:when>
 <xsl:when test="$code='nor'"><xsl:text>النرويجية</xsl:text></xsl:when>
 <xsl:when test="$code='nob'"><xsl:text>النرويجية (بوكمال)</xsl:text></xsl:when>
 <xsl:when test="$code='nno'"><xsl:text>النرويجية (نينورسك)</xsl:text></xsl:when>
 <xsl:when test="$code='nub'"><xsl:text>اللغات النوبية</xsl:text></xsl:when>
 <xsl:when test="$code='nym'"><xsl:text>نيامويزي</xsl:text></xsl:when>
 <xsl:when test="$code='nya'"><xsl:text>نيانجا</xsl:text></xsl:when>
 <xsl:when test="$code='nyn'"><xsl:text>النيانكول</xsl:text></xsl:when>
 <xsl:when test="$code='nyo'"><xsl:text>النيورو</xsl:text></xsl:when>
 <xsl:when test="$code='nzi'"><xsl:text>النزيما</xsl:text></xsl:when>
 <xsl:when test="$code='oci'"><xsl:text>الأوكيتانية (بعد 1500)</xsl:text></xsl:when>
 <xsl:when test="$code='xal'"><xsl:text>الأويرات</xsl:text></xsl:when>
 <xsl:when test="$code='oji'"><xsl:text>الأوجيبوا</xsl:text></xsl:when>
 <xsl:when test="$code='non'"><xsl:text>الإسكندنافية القديمة</xsl:text></xsl:when>
 <xsl:when test="$code='peo'"><xsl:text>الفارسية القديمة (حوالي 600-400 قبل الميلاد)</xsl:text></xsl:when>
 <xsl:when test="$code='ori'"><xsl:text>الأوريا</xsl:text></xsl:when>
 <xsl:when test="$code='orm'"><xsl:text>الأورومو</xsl:text></xsl:when>
 <xsl:when test="$code='osa'"><xsl:text>الأوساج</xsl:text></xsl:when>
 <xsl:when test="$code='oss'"><xsl:text>الأوسيتيك</xsl:text></xsl:when>
 <xsl:when test="$code='oto'"><xsl:text>لغات أوتومي</xsl:text></xsl:when>
 <xsl:when test="$code='pal'"><xsl:text>البهلوية</xsl:text></xsl:when>
 <xsl:when test="$code='pau'"><xsl:text>البالاوية</xsl:text></xsl:when>
 <xsl:when test="$code='pli'"><xsl:text>البالية</xsl:text></xsl:when>
 <xsl:when test="$code='pam'"><xsl:text>بامبانجا</xsl:text></xsl:when>
 <xsl:when test="$code='pag'"><xsl:text>بانجاسينان</xsl:text></xsl:when>
 <xsl:when test="$code='pan'"><xsl:text>البنجابية</xsl:text></xsl:when>
 <xsl:when test="$code='pap'"><xsl:text>البابيامينتو</xsl:text></xsl:when>
 <xsl:when test="$code='paa'"><xsl:text>البابوانية (أخرى)</xsl:text></xsl:when>
 <xsl:when test="$code='per'"><xsl:text>الفارسية</xsl:text></xsl:when>
 <xsl:when test="$code='phi'"><xsl:text>الفلبينية (أخرى)</xsl:text></xsl:when>
 <xsl:when test="$code='phn'"><xsl:text>الفينيقية</xsl:text></xsl:when>
 <xsl:when test="$code='pon'"><xsl:text>بونبيان</xsl:text></xsl:when>
 <xsl:when test="$code='pol'"><xsl:text>البولندية</xsl:text></xsl:when>
 <xsl:when test="$code='por'"><xsl:text>البرتغالية</xsl:text></xsl:when>
 <xsl:when test="$code='pra'"><xsl:text>لغات براكريت</xsl:text></xsl:when>
 <xsl:when test="$code='pro'"><xsl:text>البروفانسية (حتى 1500)</xsl:text></xsl:when>
 <xsl:when test="$code='pus'"><xsl:text>البشتوية</xsl:text></xsl:when>
 <xsl:when test="$code='que'"><xsl:text>الكيشوا</xsl:text></xsl:when>
 <xsl:when test="$code='roh'"><xsl:text>الرايتو-رومانسية</xsl:text></xsl:when>
 <xsl:when test="$code='raj'"><xsl:text>الراجاستانية</xsl:text></xsl:when>
 <xsl:when test="$code='rap'"><xsl:text>رابا نوي</xsl:text></xsl:when>
 <xsl:when test="$code='rar'"><xsl:text>راروتونغان</xsl:text></xsl:when>
 <xsl:when test="$code='roa'"><xsl:text>الرومانسية (أخرى)</xsl:text></xsl:when>
 <xsl:when test="$code='rom'"><xsl:text>الرومانية</xsl:text></xsl:when>
 <xsl:when test="$code='rum'"><xsl:text>الرومانية</xsl:text></xsl:when>
 <xsl:when test="$code='run'"><xsl:text>الرندي</xsl:text></xsl:when>
 <xsl:when test="$code='rus'"><xsl:text>الروسية</xsl:text></xsl:when>
 <xsl:when test="$code='sal'"><xsl:text>لغات ساليشية</xsl:text></xsl:when>
 <xsl:when test="$code='sam'"><xsl:text>السامرية الآرامية</xsl:text></xsl:when>
 <xsl:when test="$code='smi'"><xsl:text>السامي</xsl:text></xsl:when>
 <xsl:when test="$code='smo'"><xsl:text>الساموية</xsl:text></xsl:when>
 <xsl:when test="$code='sad'"><xsl:text>السانداوي</xsl:text></xsl:when>
 <xsl:when test="$code='sag'"><xsl:text>سانجو (الكريولية الأوبانغية)</xsl:text></xsl:when>
 <xsl:when test="$code='san'"><xsl:text>السنسكريتية</xsl:text></xsl:when>
 <xsl:when test="$code='sat'"><xsl:text>الصانتالية</xsl:text></xsl:when>
 <xsl:when test="$code='srd'"><xsl:text>السردينية</xsl:text></xsl:when>
 <xsl:when test="$code='sas'"><xsl:text>الساساك</xsl:text></xsl:when>
 <xsl:when test="$code='sco'"><xsl:text>الأسكتلندية</xsl:text></xsl:when>
 <xsl:when test="$code='gla'"><xsl:text>الغيلية الاسكتلندية</xsl:text></xsl:when>
 <xsl:when test="$code='sel'"><xsl:text>السيلكب</xsl:text></xsl:when>
 <xsl:when test="$code='sem'"><xsl:text>السامية (أخرى)</xsl:text></xsl:when>
 <xsl:when test="$code='srp'"><xsl:text>الصربية</xsl:text></xsl:when>
 <xsl:when test="$code='srr'"><xsl:text>السرسرية</xsl:text></xsl:when>
 <xsl:when test="$code='shn'"><xsl:text>شان</xsl:text></xsl:when>
 <xsl:when test="$code='sna'"><xsl:text>الشونا</xsl:text></xsl:when>
 <xsl:when test="$code='iii'"><xsl:text>سيتشوان يي</xsl:text></xsl:when>
 <xsl:when test="$code='scn'"><xsl:text>الإيطالية الصقلية</xsl:text></xsl:when>
 <xsl:when test="$code='sid'"><xsl:text>سيدامو</xsl:text></xsl:when>
 <xsl:when test="$code='sgn'"><xsl:text>لغات الإشارة</xsl:text></xsl:when>
 <xsl:when test="$code='bla'"><xsl:text>سيكسيكا</xsl:text></xsl:when>
 <xsl:when test="$code='snd'"><xsl:text>السندية</xsl:text></xsl:when>
 <xsl:when test="$code='sin'"><xsl:text>السنهالية</xsl:text></xsl:when>
 <xsl:when test="$code='sit'"><xsl:text>الصينية التبتية (أخرى)</xsl:text></xsl:when>
 <xsl:when test="$code='sio'"><xsl:text>سيوان (أخرى)</xsl:text></xsl:when>
 <xsl:when test="$code='sms'"><xsl:text>سكولت سامي</xsl:text></xsl:when>
 <xsl:when test="$code='den'"><xsl:text>سلافي</xsl:text></xsl:when>
 <xsl:when test="$code='sla'"><xsl:text>السلافية (أخرى)</xsl:text></xsl:when>
 <xsl:when test="$code='slo'"><xsl:text>السلوفاكية</xsl:text></xsl:when>
 <xsl:when test="$code='slv'"><xsl:text>السلوفينية</xsl:text></xsl:when>
 <xsl:when test="$code='sog'"><xsl:text>سوغديان</xsl:text></xsl:when>
 <xsl:when test="$code='som'"><xsl:text>الصومالية</xsl:text></xsl:when>
 <xsl:when test="$code='son'"><xsl:text>السونغاي</xsl:text></xsl:when>
 <xsl:when test="$code='snk'"><xsl:text>السوننكية</xsl:text></xsl:when>
 <xsl:when test="$code='wen'"><xsl:text>الصربية (أخرى)</xsl:text></xsl:when>
 <xsl:when test="$code='sot'"><xsl:text>السوتو الشمالية</xsl:text></xsl:when>
 <xsl:when test="$code='sai'"><xsl:text>الهندية الأمريكية الجنوبية (أخرى)</xsl:text></xsl:when>
 <xsl:when test="$code='sma'"><xsl:text>السامي الجنوبية</xsl:text></xsl:when>
 <xsl:when test="$code='spa'"><xsl:text>الأسبانية</xsl:text></xsl:when>
 <xsl:when test="$code='srn'"><xsl:text>سرانان</xsl:text></xsl:when>
 <xsl:when test="$code='suk'"><xsl:text>السوكوما</xsl:text></xsl:when>
 <xsl:when test="$code='sux'"><xsl:text>السومارية</xsl:text></xsl:when>
 <xsl:when test="$code='sun'"><xsl:text>السودانية</xsl:text></xsl:when>
 <xsl:when test="$code='sus'"><xsl:text>السوسو</xsl:text></xsl:when>
 <xsl:when test="$code='swa'"><xsl:text>السواحيلية</xsl:text></xsl:when>
 <xsl:when test="$code='ssw'"><xsl:text>السوازيلاندية</xsl:text></xsl:when>
 <xsl:when test="$code='swe'"><xsl:text>السويدية</xsl:text></xsl:when>
 <xsl:when test="$code='gsw'"><xsl:text>الألمانية السويسرية</xsl:text></xsl:when>
 <xsl:when test="$code='syc'"><xsl:text>السريانية</xsl:text></xsl:when>
 <xsl:when test="$code='syr'"><xsl:text>السريانية الحديثة</xsl:text></xsl:when>
 <xsl:when test="$code='tgl'"><xsl:text>التاغالوغية</xsl:text></xsl:when>
 <xsl:when test="$code='tah'"><xsl:text>التاهيتية</xsl:text></xsl:when>
 <xsl:when test="$code='tai'"><xsl:text>التايلندية (أخرى)</xsl:text></xsl:when>
 <xsl:when test="$code='tgk'"><xsl:text>الطاجكستانية</xsl:text></xsl:when>
 <xsl:when test="$code='tmh'"><xsl:text>التمشق</xsl:text></xsl:when>
 <xsl:when test="$code='tam'"><xsl:text>التاميل</xsl:text></xsl:when>
 <xsl:when test="$code='tat'"><xsl:text>التتارية</xsl:text></xsl:when>
 <xsl:when test="$code='tel'"><xsl:text>التيلوغوية</xsl:text></xsl:when>
 <xsl:when test="$code='tem'"><xsl:text>التيمني</xsl:text></xsl:when>
 <xsl:when test="$code='ter'"><xsl:text>تيرينا</xsl:text></xsl:when>
 <xsl:when test="$code='tet'"><xsl:text>التيتومية</xsl:text></xsl:when>
 <xsl:when test="$code='tha'"><xsl:text>تايلاندي</xsl:text></xsl:when>
 <xsl:when test="$code='tib'"><xsl:text>التبتية</xsl:text></xsl:when>
 <xsl:when test="$code='tig'"><xsl:text>تيغري</xsl:text></xsl:when>
 <xsl:when test="$code='tir'"><xsl:text>التيغرينية</xsl:text></xsl:when>
 <xsl:when test="$code='tiv'"><xsl:text>التيف</xsl:text></xsl:when>
 <xsl:when test="$code='tli'"><xsl:text>التلينغيتية</xsl:text></xsl:when>
 <xsl:when test="$code='tpi'"><xsl:text>توك بيسين</xsl:text></xsl:when>
 <xsl:when test="$code='tkl'"><xsl:text>التوكيلاوية</xsl:text></xsl:when>
 <xsl:when test="$code='tog'"><xsl:text>تونجا (نياسا)</xsl:text></xsl:when>
 <xsl:when test="$code='ton'"><xsl:text>التونغية</xsl:text></xsl:when>
 <xsl:when test="$code='tsi'"><xsl:text>التسيمشيان</xsl:text></xsl:when>
 <xsl:when test="$code='tso'"><xsl:text>تسونغا</xsl:text></xsl:when>
 <xsl:when test="$code='tsn'"><xsl:text>التسوانية</xsl:text></xsl:when>
 <xsl:when test="$code='tum'"><xsl:text>تومبوكا</xsl:text></xsl:when>
 <xsl:when test="$code='tup'"><xsl:text>لغات توبي</xsl:text></xsl:when>
 <xsl:when test="$code='tur'"><xsl:text>التركية</xsl:text></xsl:when>
 <xsl:when test="$code='ota'"><xsl:text>التركية العثمانية</xsl:text></xsl:when>
 <xsl:when test="$code='tuk'"><xsl:text>التركمانية</xsl:text></xsl:when>
 <xsl:when test="$code='tvl'"><xsl:text>التوفالية</xsl:text></xsl:when>
 <xsl:when test="$code='tyv'"><xsl:text>التوفينية</xsl:text></xsl:when>
 <xsl:when test="$code='twi'"><xsl:text>التوي</xsl:text></xsl:when>
 <xsl:when test="$code='udm'"><xsl:text>الأدمرتية</xsl:text></xsl:when>
 <xsl:when test="$code='uga'"><xsl:text>الأوغاريتية</xsl:text></xsl:when>
 <xsl:when test="$code='uig'"><xsl:text>الأيغورية</xsl:text></xsl:when>
 <xsl:when test="$code='ukr'"><xsl:text>الأوكرانية</xsl:text></xsl:when>
 <xsl:when test="$code='umb'"><xsl:text>أومبوندو</xsl:text></xsl:when>
 <xsl:when test="$code='und'"><xsl:text>غير محدد </xsl:text></xsl:when>
 <xsl:when test="$code='hsb'"><xsl:text>الصربية العليا</xsl:text></xsl:when>
 <xsl:when test="$code='urd'"><xsl:text>الأردية</xsl:text></xsl:when>
 <xsl:when test="$code='uzb'"><xsl:text>الأوزبكية</xsl:text></xsl:when>
 <xsl:when test="$code='vai'"><xsl:text>الفاي</xsl:text></xsl:when>
 <xsl:when test="$code='ven'"><xsl:text>الفيندا</xsl:text></xsl:when>
 <xsl:when test="$code='vie'"><xsl:text>الفيتنامية</xsl:text></xsl:when>
 <xsl:when test="$code='vol'"><xsl:text>فولابوك</xsl:text></xsl:when>
 <xsl:when test="$code='vot'"><xsl:text>الفوتيك</xsl:text></xsl:when>
 <xsl:when test="$code='wak'"><xsl:text>لغات واكشان</xsl:text></xsl:when>
 <xsl:when test="$code='wln'"><xsl:text>الولونية</xsl:text></xsl:when>
 <xsl:when test="$code='war'"><xsl:text>الواراي</xsl:text></xsl:when>
 <xsl:when test="$code='was'"><xsl:text>واشو</xsl:text></xsl:when>
 <xsl:when test="$code='wel'"><xsl:text>الويلزية</xsl:text></xsl:when>
 <xsl:when test="$code='him'"><xsl:text>لغات البهارية الغربية</xsl:text></xsl:when>
 <xsl:when test="$code='wal'"><xsl:text>وولايتا</xsl:text></xsl:when>
 <xsl:when test="$code='wol'"><xsl:text>الولوف</xsl:text></xsl:when>
 <xsl:when test="$code='xho'"><xsl:text>زوسا</xsl:text></xsl:when>
 <xsl:when test="$code='sah'"><xsl:text>ياكوت</xsl:text></xsl:when>
 <xsl:when test="$code='yao'"><xsl:text>ياو (إفريقيا)</xsl:text></xsl:when>
 <xsl:when test="$code='yap'"><xsl:text>اليابية</xsl:text></xsl:when>
 <xsl:when test="$code='yid'"><xsl:text>اليديشية</xsl:text></xsl:when>
 <xsl:when test="$code='yor'"><xsl:text>اليوروبية</xsl:text></xsl:when>
 <xsl:when test="$code='ypk'"><xsl:text>لغات يوبيك</xsl:text></xsl:when>
 <xsl:when test="$code='znd'"><xsl:text>لغات زاندي</xsl:text></xsl:when>
 <xsl:when test="$code='zap'"><xsl:text>زابوتك</xsl:text></xsl:when>
 <xsl:when test="$code='zza'"><xsl:text>زازا</xsl:text></xsl:when>
 <xsl:when test="$code='zen'"><xsl:text>زيناغا</xsl:text></xsl:when>
 <xsl:when test="$code='zha'"><xsl:text>تشوانغ</xsl:text></xsl:when>
 <xsl:when test="$code='zul'"><xsl:text>الزولو</xsl:text></xsl:when>
 <xsl:when test="$code='zun'"><xsl:text>زوني</xsl:text></xsl:when>
 <xsl:otherwise>
 <!-- when 041$a is mapped to an authorised value list, this will show the description -->
 <xsl:value-of select="$code" />
 </xsl:otherwise>
 </xsl:choose>
 </xsl:template>
</xsl:stylesheet>
