<fieldset>
 <legend>الحقول المشفرة</legend>
 <p>
 <label>جمهور</label>
 <select name="limit" class="subtype">
 <option value="" selected="selected" >أي</option>
 <option value="aud:a">حدث ، عام</option>
 <option value="aud:b">pre-primary (0-5)</option>
 <option value="aud:c">أولي (5-8)</option>
 <option value="aud:d">الأطفال (9-14)</option>
 <option value="aud:e">شاب</option>
 <option value="aud:k">بالغ، جدي</option>
 <option value="aud:m">بالغ, عام</option>
 <option value="aud:u">غير معروف</option>
 </select>
 </p>
 <p>
 <label>العرض المادي</label>
 <select name="limit" class="subtype">
 <option value="" selected="selected" >أي</option>
 <option value="Material-type:r">طبعة منتظمة</option>
 <option value="Material-type:d">طبعة كبيرة</option>
 <option value="Material-type:e">تنسيق جريدة</option>
 <option value="Material-type:f">نص بلغة بريل أو مون</option>
 <option value="Material-type:g">طبعة مصغرة</option>
 <option value="Material-type:h">كتابة يدوية</option>
 <option value="Material-type:i">وسائط متعددة</option>
 <option value="Material-type:j">طبعة مصغرة</option>
 <option value="Material-type:s">مصادر إلكتروني</option>
 <option value="Material-type:t">ميكروفورم</option>
 <option value="Material-type:z">شكل آخر من اشكال المواد النصية</option>
 </select>
 </p>
 <p>
 <label>نوع أدبي</label>
 <select name="limit" class="subtype">
 <option value="" selected="selected" >أي</option>
 <option value="Literature-Code:a">خيال</option>
 <option value="Literature-Code:b">دراما </option>
 <option value="Literature-Code:c">مقالات</option>
 <option value="Literature-Code:d">دعابة ، سخرية</option>
 <option value="Literature-Code:e">الرسالة</option>
 <option value="Literature-Code:f">قصص قصيرة</option>
 <option value="Literature-Code:g">شعر</option>
 <option value="Literature-Code:h">خطب, فن الخطابة</option>
 <option value="Literature-Code:i">نص كلام الأوبرا</option>
 <option value="Literature-Code:y">ليس نص أدبي</option>
 <option value="Literature-Code:z">أشكال أدبية متعددة/أخرى</option>
 </select>
 </p>
 <p>
 <label>السيرة الذاتية</label>
 <select name="limit" class="subtype">
 <option value="">أي</option>
 <option value="Biography-code:y">ليست سيرة ذاتية</option>
 <option value="Biography-code:a">السيرة الذاتية</option>
 <option value="Biography-code:b">سيرة ذاتية فردية</option>
 <option value="Biography-code:c">سيرة جماعية</option>
 <option value="Biography-code:d">يحتوي على بيانات سيرة ذاتية</option>
 </select>
 </p>
 <p>
 <label>الإيضاح</label>
 <select name="limit" class="subtype">
 <option value="">أي</option>
 <option value="Illustration-Code:a">توضيحات</option>
 <option value="Illustration-Code:b">خرائط</option>
 <option value="Illustration-Code:c">صور</option>
 <option value="Illustration-Code:d">خرائط بيانية</option>
 <option value="Illustration-Code:e">خطط</option>
 <option value="Illustration-Code:f">لوحات</option>
 <option value="Illustration-Code:g">موسيقى</option>
 <option value="Illustration-Code:h">صور طبق الأصل</option>
 <option value="Illustration-Code:i">شعارات</option>
 <option value="Illustration-Code:j">جداول الأنساب</option>
 <option value="Illustration-Code:k">أشكال</option>
 <option value="Illustration-Code:l">عيّنات</option>
 <option value="Illustration-Code:m">تسجيلات صوتية</option>
 <option value="Illustration-Code:n">شفافيات</option>
 <option value="Illustration-Code:o">زخارف</option>
 <option value="Illustration-Code:y">لا ايضاحات</option>
 </select>
 </p>
 <p>
 <label>المحتوى</label>
 <select name="limit" class="subtype">
 <option value="" >أي</option>
 <option value="ctype:a" >الببليوغرافية</option>
 <option value="ctype:b" >الفهرس</option>
 <option value="ctype:c" >فهرس</option>
 <option value="ctype:d" >تجريدي</option>
 <option value="ctype:e" >قاموس </option>
 <option value="ctype:f" >موسوعة</option>
 <option value="ctype:g" >دليل</option>
 <option value="ctype:h" >وصف الموضوع</option>
 <option value="ctype:i" >إحصائيات</option>
 <option value="ctype:j" >نصوص كتب مبرمجة</option>
 <option value="ctype:k" >براءات الاختراع</option>
 <option value="ctype:l" >قياسي</option>
 <option value="ctype:m" >رسالة جامعية أو أطروحة</option>
 <option value="ctype:n" >قوانين وتشريعات</option>
 <option value="ctype:o" > جدول رقمي</option>
 <option value="ctype:p" >تقرير تقني</option>
 <option value="ctype:q" >ورقة إمتحان</option>
 <option value="ctype:r" >استطلاعات أدبية/مراجعات</option>
 <option value="ctype:s" >اتفاقيات</option>
 <option value="ctype:t" >كارتون أو أشرطة هزلية</option>
 <option value="ctype:v" >رسالة جامعية أو أطروحة (منقحة)</option>
 <option value="ctype:w" >نص ديني</option>
 <option value="ctype:z" >آخر</option>
 </select>
 </p>
 <p>
 <label>أنواع الفيديو</label>
 <select name="limit" class="subtype">
 <option value="">أي</option>
 <option value="Video-mt:a">صورة متحركة</option>
 <option value="Video-mt:b">اسقاط بصري</option>
 <option value="Video-mt:c">تسجيل فيديو</option>
 </select>
 </p>
</fieldset>

<fieldset>
 <legend>الدوريات</legend><p>
 <p>
 <label>نوع السلسلة</label>
 <select name="limit" class="subtype">
 <option value="">أي نوع</option>
 <option value="Type-Of-Serial:a">نشرة دورية</option>
 <option value="Type-Of-Serial:b">سلسلة تخصصية</option>
 <option value="Type-Of-Serial:c">جريدة</option>
 <option value="Type-Of-Serial:e">تحديث loose-leaf</option>
 <option value="Type-Of-Serial:f">قاعدة البيانات</option>
 <option value="Type-Of-Serial:g">تحديث صفحة الويب</option>
 <option value="Type-Of-Serial:z">آخر</option>
 </select>
 </p>
 <p>
 <label>بشكل دوري</label>
 <select name="limit" class="subtype">
 <option value="">أي</option>
 <option value="Frequency-code:a">يومياً</option>
 <option value="Frequency-code:b">نصف اسبوعية</option>
 <option value="Frequency-code:c">أسبوعي</option>
 <option value="Frequency-code:d">كل أسبوعين</option>
 <option value="Frequency-code:e">نصف شهرية</option>
 <option value="Frequency-code:f">شهري</option>
 <option value="Frequency-code:g">نصف شهري</option>
 <option value="Frequency-code:h">فصلي</option>
 <option value="Frequency-code:i">ثلاث مرات في السنة</option>
 <option value="Frequency-code:j">نصف سنوية</option>
 <option value="Frequency-code:k">سنوي</option>
 <option value="Frequency-code:l">كل سنتين</option>
 <option value="Frequency-code:m">كل ثلاث سنوات</option>
 <option value="Frequency-code:n">ثلاث مرات في الإسبوع</option>
 <option value="Frequency-code:o">ثلاث مرات في الشهر</option>
 <option value="Frequency-code:y">بدون تواتر</option>
 <option value="Frequency-code:u">غير معرّف</option>
 <option value="Frequency-code:z">آخر</option>
 </select>
 </p>
 <p>
 <label>الانتظام</label>
 <select name="limit" class="subtype">
 <option value="">أي انتظام</option>
 <option value="Regularity-code:a">منتظم</option>
 <option value="Regularity-code:b">عد انتظام تم تطبيعه</option>
 <option value="Regularity-code:y">غير منظم</option>
 <option value="Regularity-code:u">غير معروف</option>
 </select>
 </p>
</fieldset>

<fieldset>
 <legend>صورة</legend>
 <select name="limit" class="subtype">
 <option value="">أي</option>
 <option value="Graphics-type:a">ملصقة</option>
 <option value="Graphics-type:b">رسم </option>
 <option value="Graphics-type:c">اللوحة</option>
 <option value="Graphics-type:d">الاستنساخ الضوئي</option>
 <option value="Graphics-type:e">الصورة السلبية</option>
 <option value="Graphics-type:f">طباعة الصور</option>
 <option value="Graphics-type:h">صور</option>
 <option value="Graphics-type:i">طباعة</option>
 <option value="Graphics-type:k">رسم تقني</option>
 <option value="Graphics-type:z">نوع رسم غير معروض آخر</option>
 </select>
 <select name="limit" class="subtype">
 <option value="">أي</option>
 <option value="Graphics-support:a">كانفاه</option>
 <option value="Graphics-support:b">لوحة بريستول</option>
 <option value="Graphics-support:c">لوح كرتون/لوح شرح</option>
 <option value="Graphics-support:d">زجاج</option>
 <option value="Graphics-support:j">plaster</option>
 <option value="Graphics-support:k">الواح</option>
 <option value="Graphics-support:l">بورسلين</option>
 <option value="Graphics-support:m">حجر</option>
 <option value="Graphics-support:n">خشب</option>
 <option value="Graphics-support:v">mixed collection</option>
 <option value="Graphics-support:e">مواد تركيبية</option>
 <option value="Graphics-support:f">جلد</option>
 <option value="Graphics-support:g">نسيج</option>
 <option value="Graphics-support:h">معدن</option>
 <option value="Graphics-support:i">ورقة</option>
 <option value="Graphics-support:z">آخرون</option>
 <option value="Graphics-support:u">غير معروف</option>
 </select>
</fieldset>
